name: app
description: "A new Flutter Biology Research App project."

# Prevent accidental publication to pub.dev
publish_to: "none"

# Versioning
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  http: ^1.2.2
  provider: ^6.1.2
  firebase_auth: ^5.3.4
  google_fonts: ^6.2.1
  lottie: ^3.3.0
  smooth_page_indicator: ^1.2.0+3
  fluttertoast: ^8.2.10
  url_launcher: ^6.3.1
  get: ^4.6.6
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Asset configuration
  assets:
    - assets/

# Flutter native splash screen configuration
flutter_native_splash:
  color: "#116530"
  image: assets/foodicon.png
  android_12:
    color: "#116530"
    image: assets/foodicon.png
  android: true
  ios: true
